export const LOGIN_STATE = {
  DEFAULT: "DEFAULT",
  LOADING: "LOADING",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_RESET_LOADING: "PASSWORD_RESET_LOADING",
  PASSWORD_RESET_ERROR: "PASSWORD_RESET_ERROR",
}